### ISSUE TITLE
detail::spinlock crashes on PPC

### ISSUE THREAD

**Issue by pdimov** [boostorg/smart_ptr#105]
https://github.com/PurpleI2P/i2pd/issues/1726
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107590

Apparently, `__atomic_test_and_set` requires an operand with the alignment of `bool`, and does not necessarily support `char`, despite what the documentation says; and `bool` is 32 bit on PPC.

**Comment by pdimov** [comment]
Fixed on develop.

**Comment by barracuda156** [comment]
@pdimov Is it safe to backport?

**Comment by pdimov** [comment]
It should be.
