### ISSUE TITLE
Feature request: enable_local_shared_from_this

### ISSUE THREAD

**Issue by FooBarWidget** [boostorg/smart_ptr#52]
I would like to use `local_shared_ptr` because I need the performance and don't need the synchronization guarantees. But this library is currently lacking local version of `enable_shared_from_this`. I would like to request such a feature addition.

**Comment by pdimov** [comment]
There is no need for a separate local base class; use `enable_shared_from_this` and assign the result of `shared_from_this` to `local_shared_ptr`.

As currently implemented, it's not possible to make the hypothetical `local_shared_from_this` more efficient than the ordinary `shared_from_this`, even if all such calls are guaranteed to originate from the same thread.
