### ISSUE TITLE
make_local_shared does not accept a const type

### ISSUE THREAD

**Issue by cinghiale** [boostorg/smart_ptr#54]
Differently from std::make_shared and boost::make_shared, boost::make_local_shared does not accept a const type.

```cpp
#include <boost/smart_ptr/make_local_shared.hpp>

auto h() {
    return boost::make_local_shared<const int>();
}
```

This snippet fails to compile because make_local_shared tries to construct a std::allocator<const inst>.

You can check it online on godbolt: https://gcc.godbolt.org/z/ghQWbM

**Comment by pdimov** [comment]
Fixed in https://github.com/boostorg/smart_ptr/commit/f6c3508aeed7d6f3838015713c480090371e154d. Sorry for the delay.
