### ISSUE TITLE
Naive question about atomic_sp_constexpr_test.cpp

### ISSUE THREAD

**Issue by dkrejsa** [boostorg/smart_ptr#62]
Hi,
I'm not much more than a C++ beginner, but I'm involved in the effort to get Boost supported better on VxWorks.  One of the tests that is failing across all our targets is the atomic_sp_constexpr_test.

In that test there are static objects created:

    static Z z;

    static boost::atomic_shared_ptr<X> p1;

Further, the constructor Z() assigns to the static object p1:

    Z::Z()
    {
        p1 = boost::shared_ptr<X>( new X );
    }

Now, it seems this test is failing because by the time main() runs, p1 has been zeroed.
I think that since z is defined before p1, the constructor for z runs before the constructor for
p1; Z::Z() assigns to the un-initialized p1.  But then the constructor for p1 runs and reinitializes
p1. (In fact, on an Intel target, immediately after the call to Z::Z() are some move instructions
that zero p1.)

This all runs before main().  In main(), a new shared pointer p2 is set equal to p1, and the
test expects that p2 contains a non-nullptr pointer, and that p2.use_count is 2.  But since p1 has
been zeroed, this fails.

So, I'm not sure how this test is supposed to work, and also, how is it related to _constexpr_ ?

We're building with llvm 7, and/or gnu 8.1.

**Comment by pdimov** [comment]
It's testing whether the initialization of `p1` is static (not performed at runtime.)

Such initialization is performed in C++11 when the constructor is `constexpr`.

What standard library are you using?

**Comment by dkrejsa** [comment]
We use the Dinkum C/C++  library.

**Comment by dkrejsa** [comment]
Wow, thank you very much!

**Comment by pdimov** [comment]
This test fails on popular compilers such as MSVC and on popular standard libraries such as libc++ (as you can see from the ifdefs in it), so it's not a big issue if it fails for VxWorks too.

**Comment by dkrejsa** [comment]
Hi pdimov,
I added [[clang::require_constant_initialization]] as you suggested, and indeed the resulting error message pointed at the constructor for std::atomic_flag not being constexpr.
(Simply adding constexpr to the std::atomic_flag constructor definition made the test pass.  I don't see a reason why the constructor shouldn't be constexpr, but I'm a neophyte.  I'll try to ask someone locally who knows a bit more than me.)   In any case, thanks again.
