### ISSUE TITLE
Assembler-Error with boost on AIX with gcc8

### ISSUE THREAD

**Issue by Flow86** [boostorg/smart_ptr#65]
Hi,

I am using boost on an AIX 7.2 host with IBM Linux Toolbox. 
We used the old gcc 4.6.3 until now and tried upgrading to the official gcc 8.2 version by IBM.

We now get an "as: Syntax error" with the new gcc coming from th file `boost/include/boost/smart_ptr/detail/sp_counted_base_gcc_ppc.hpp`.

At the moment, we're using boost 1.62, but the file was not changed on a newer boost version.

Exactly, the numeric labels in the inline assembler code ("0:") is causing the problem.
I changed the inline assembler to use non numeric labels now:

```
--- a/boost/include/boost/smart_ptr/detail/sp_counted_base_gcc_ppc.hpp  2017-06-06 18:19:26.000000000 +0200
+++ b/boost/include/boost/smart_ptr/detail/sp_counted_base_gcc_ppc.hpp   2019-03-07 11:16:37.000000000 +0100
@@ -40,11 +40,11 @@

      __asm__
      (
-         "0:\n\t"
+         "loop%=:\n\t"
          "lwarx %1, 0, %2\n\t"
          "addi %1, %1, 1\n\t"
          "stwcx. %1, 0, %2\n\t"
-         "bne- 0b":
+         "bne- loop%=":

          "=m"( *pw ), "=&b"( tmp ):
          "r"( pw ), "m"( *pw ):
@@ -61,11 +61,11 @@
      __asm__ __volatile__
      (
          "sync\n\t"
-         "0:\n\t"
+         "loop%=:\n\t"
          "lwarx %1, 0, %2\n\t"
          "addi %1, %1, -1\n\t"
          "stwcx. %1, 0, %2\n\t"
-         "bne- 0b\n\t"
+         "bne- loop%=\n\t"
          "isync":

          "=m"( *pw ), "=&b"( rv ):
@@ -85,14 +85,14 @@

      __asm__
      (
-         "0:\n\t"
+         "loop%=:\n\t"
          "lwarx %1, 0, %2\n\t"
          "cmpwi %1, 0\n\t"
-         "beq 1f\n\t"
+         "beq store%=\n\t"
          "addi %1, %1, 1\n\t"
-         "1:\n\t"
+         "store%=:\n\t"
          "stwcx. %1, 0, %2\n\t"
-         "bne- 0b":
+         "bne- loop%=":

          "=m"( *pw ), "=&b"( rv ):
          "r"( pw ), "m"( *pw ):
```

I'm not so extremely firm with ASM (yet), so did I do that correctly?

**Comment by pdimov** [comment]
This looks correct, even though I have no way to verify it. Would you submit a pull request?

**Comment by Flow86** [comment]
I still find it weird why https://github.com/boostorg/smart_ptr/blob/develop/include/boost/smart_ptr/detail/sp_counted_base_aix.hpp isnt used. Perhaps it really was only a bug in the old boost version: https://github.com/boostorg/smart_ptr/commit/16084637a6b5eb188cbd07f71cddf4eca43a66c1#diff-eca044534514a8ecf9b8450be1422f9c

**Comment by pdimov** [comment]
This commit references https://svn.boost.org/trac10/ticket/6996, but it doesn't shed much light.

**Comment by pdimov** [comment]
The `_AIX` path was mistakenly removed in https://github.com/boostorg/smart_ptr/commit/1029ae0ea5497db1a6884d129cb2bc4d9d238bc8#diff-eca044534514a8ecf9b8450be1422f9c and then reinstated in https://github.com/boostorg/smart_ptr/commit/03ae5cdbc69854d5c5c8f597153e4832b9c4cc76#diff-eca044534514a8ecf9b8450be1422f9c.

**Comment by pdimov** [comment]
This all happened in Boost 1.56, so it should be in 1.62 too. Perhaps the new GCC doesn't define `_AIX`?

**Comment by Flow86** [comment]
it does, but I also can't reproduce it at the moment. Weird thing ...
