### ISSUE TITLE
Memoryleak in combination with std::set

### ISSUE THREAD

**Issue by geraldmwangi** [boostorg/smart_ptr#71]
## Subject: Memory leak in boost smart_ptr 1.65 
I have discovered a strange bug/memory leak when combining shared_ptr with std::set. 
The following sample code is self contained, all you need is:
## Dependencies
Linux (I tested it on Ubuntu 18.04)
libboost1.65-dev from the repos
valgrind

## Sample Code
[boostBug.zip](https://github.com/boostorg/smart_ptr/files/3717378/boostBug.zip)

**Comment by geraldmwangi** [comment]
The same leak also occurs with std::vector

**Comment by geraldmwangi** [comment]
In line 83 in sharedptr.cpp: Forget the comment "//cl3 takes ownership of cl". I wanted to design it that way (so that I don't have to delete cl ) but that would have complicated the code, so I KISS

**Comment by glenfe** [comment]
You're creating a cycle with your `candidateCluster->elements = elements;` assignment. The problem you have can effectively be reduced to the following (which doesn't even involve `std::set` at all):

```
#include <boost/make_shared.hpp>

class S {
public:
    typedef boost::shared_ptr<S> P;
    void f(P p) {
        p_ = p;
        p->p_ = p_;
    }
private:
    P p_;
    char c_[3000000];
};

int main()
{
    S::P x = boost::make_shared<S>();
    S::P y = boost::make_shared<S>();
    y->f(x);
}
```

**Comment by geraldmwangi** [comment]
But why does this leak? If you substitute the shared ptr's with ordinary c++ pointers, it won't leak despite the member x.p_ pointing to x itself after y->f(x).
Is the constructor of class S called multiple times when copying share_ptr's of type boost::shared_ptr<S>?

**Comment by geraldmwangi** [comment]
Thanks for taking the time to break down my code to a simpler form :)

**Comment by geraldmwangi** [comment]
Ok got it now after bringing it to the point:
#include <boost/make_shared.hpp>

class S {
public:
    typedef boost::shared_ptr<S> P;
    P p_;
    char c_[3000000];
};

int main()
{
    S::P x = boost::make_shared<S>();
    x->p_ = x;
}
