### ISSUE TITLE
Clang warning 

### ISSUE THREAD

**Issue by DarkerStar** [boostorg/smart_ptr#78]
(Sorry, accidentally hit wrong key and posted this while still writing - in fact while writing the title.)

Clang 11 generates a warning when compiling with just "`-pedantic`":

```
$ clang++ -pedantic -I/mnt/saturn/source/boost_1_72_0 -c -o main.o main.cpp
In file included from main.cpp:1:
In file included from /mnt/saturn/source/boost_1_72_0/boost/smart_ptr.hpp:19:
In file included from /mnt/saturn/source/boost_1_72_0/boost/shared_ptr.hpp:17:
In file included from /mnt/saturn/source/boost_1_72_0/boost/smart_ptr/shared_ptr.hpp:28:
In file included from /mnt/saturn/source/boost_1_72_0/boost/smart_ptr/detail/shared_count.hpp:29:
In file included from /mnt/saturn/source/boost_1_72_0/boost/smart_ptr/detail/sp_counted_base.hpp:45:
/mnt/saturn/source/boost_1_72_0/boost/smart_ptr/detail/sp_counted_base_clang.hpp:29:9: warning: '_Atomic' is a C11 extension [-Wc11-extensions]
typedef _Atomic( boost::int_least32_t ) atomic_int_least32_t;
        ^
1 warning generated.
$ cat main.cpp
#include <boost/smart_ptr.hpp>

int main() {}
$ clang++ --version
clang version 11.0.0-++20200414060218+d1a677cd33e-1~exp1~20200414040817.489 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

(Boost 1.72.0 source acquired by downloading the tar.gz from the boost.org site.)

**Comment by pdimov** [comment]
Where would we be without pedantry :-)

**Comment by pdimov** [comment]
Is this warning new in Clang 11, or do earlier versions emit it too?

**Comment by DarkerStar** [comment]
I only have 7, 8, and 9 installed, and Wandbox doesn't seem to support Boost with 10. It *looks* new in 11.

**Comment by pdimov** [comment]
Godbolt uses -isystem, so it doesn't emit warnings from Boost.

**Comment by pdimov** [comment]
Seems that Clang 10 also has it: https://godbolt.org/z/r2VGme

**Comment by pdimov** [comment]
Should be fixed on develop by https://github.com/boostorg/smart_ptr/commit/066b398114ab48c81c875e95459c15c2416a7891.

**Comment by DarkerStar** [comment]
Yup, warning's gone!
